#!/usr/bin/env bash

export BROWSER=${BROWSER:="firefox"}  # use 'firefox' if BROWSER isn't set

export CI_TEST_ENV=${CI_TEST_ENV:="TRUE"}  # disable keycloak_role_auth in testing

export LTA_MONGODB_DATABASE_NAME=${LTA_MONGODB_DATABASE_NAME:="lta"}
export LTA_MONGODB_HOST=${LTA_MONGODB_HOST:="localhost"}
export LTA_MONGODB_PORT=${LTA_MONGODB_PORT:="27017"}

function check {
    python3 -m resources.check_requirements
}

function clean {
    rm -fr .coverage
    rm -fr .mypy_cache
    rm -fr .pytest_cache
    rm -fr build
    rm -fr dist
    rm -fr htmlcov
    find lta -name __pycache__ -exec rm -fr {} +
    find lta -name __init__.pyc -exec rm -fr {} +
    rm -fr lta.egg-info
    find resources -name __pycache__ -exec rm -fr {} +
    find resources -name __init__.pyc -exec rm -fr {} +
    find tests -name __pycache__ -exec rm -fr {} +
    find tests -name __init__.pyc -exec rm -fr {} +
}

function coverage {
    pytest --cov=file_catalog --cov-report=html --no-cov-on-fail ${2:-'tests'}  # use 'tests' if a module wasn't provided
    ${BROWSER} --new-tab htmlcov/index.html
}

function dist {
    rebuild
    python3 setup.py sdist bdist_wheel
}

function lint {
    flake8 lta
    mypy --strict --allow-subclassing-any --namespace-packages lta
    flake8 resources
    mypy --strict --allow-subclassing-any resources
    flake8 tests
    mypy --strict --allow-subclassing-any tests
}

function mongo {
    docker stop test-mongo
    docker pull circleci/mongo:latest-ram
    docker run \
        --detach \
        --name test-mongo \
        --network=host \
        --rm \
        circleci/mongo:latest-ram
}

function rebuild {
    clean
    lint
    test
}

function test {
    # See: https://docs.pytest.org/en/7.1.x/how-to/usage.html#specifying-which-tests-to-run
    # $0   $1   $2                  $3
    # suru test tests/test_files.py test_10_files
    if [[ ! -z "$3" ]]; then
        export PYTEST_ADDOPTS="${PYTEST_ADDOPTS} -k $3"
    fi

    pytest -ra ${2:-'tests'}  # use 'tests' if a module wasn't provided
}

case "$1" in
    check)    check         ;;
    clean)    clean         ;;
    coverage) coverage "$@" ;;  # pass all command line args to coverage function
    dist)     dist          ;;
    lint)     lint          ;;
    mongo)    mongo         ;;
    rebuild)  rebuild       ;;
    test)     test "$@"     ;;  # pass all command line args to test function
    *)
        echo "Usage: $0 {check|clean|coverage|dist|lint|mongo|rebuild|test}"
        exit 1
esac

exit 0
