version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.2
              environment:
                LTA_MONGODB_URL: mongodb://localhost:27017
            - image: circleci/mongo:3.7.9-ram
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                ./snake rebuild
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
