version: 2
jobs:
    test:
        docker:
            - image: circleci/python:latest
              environment:
                LTA_MONGODB_URL: mongodb://localhost:27017
                LTA_MONGODB_NAME: lta-unit-tests
            - image: circleci/mongo:latest-ram
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                pycycle --here --verbose &&
                resources/enable_profiling.py &&
                ./snake rebuild &&
                resources/profile_queries.py
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
