#!/bin/bash
eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/setup.sh`
source /home/jadelta/LTA/lta/env/bin/activate
cd /home/jadelta/dumpcontrol/DumpStream/jadetools
nnn=$(date +%s)
python InterfaceLTA.py >& "/mnt/lfs7/ltatemp/log/INT${nnn}.log" &
