#!/bin/bash
xxx=`python -c "import random; print(random.randrange(5,9))"`
cd /home/jadelta/LTA/lta
eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/setup.sh`
source /home/jadelta/LTA/lta/env/bin/activate
/home/jadelta/LTA/lta/bin/pipe1-gridftp-replicator.sh ${xxx}
