name: 'Docker'

on:
  # only on tag pushes
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'an additional tag to publish and possibly overwrite'
        default: 'dev'
        required: false


jobs:
  image-publish:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@v1.14
    permissions: # for GITHUB_TOKEN
      packages: write
    with:
      image_registry: ghcr.io
      image_namespace: wipacrepo
      image_name: lta
      mode: 'BUILD'
      extra_build_tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || '' }}
