name: 'GitHub'

on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository_owner == 'WIPACrepo'
    name: "Semantic Release"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # pypi_token: ${{ secrets.PYPI_TOKEN }}
